### ISSUE TITLE
Text styles

### ISSUE THREAD

**Issue by mjsxi** [gossi/figma-theemo#1]
Hi there, I was wondering if there was any plans to expand the plugin features to allow for the creation of text style references?

**Comment by gossi** [comment]
Yes, absolutely! I will also need them. I for now only did work with rectangles and its styles... that's why I focused these styles first.

**Comment by mjsxi** [comment]
Oh nice!! Was just curious since I'm super interested in this — thanks for the reply 😄

**Comment by gossi** [comment]
We'll keep it open, so its fingerpointing at me now ;) I'll close it once you are able to use it. I like that more :)

**Comment by gossi** [comment]
With the latest release (and rename to "Theemo"), text styles are finally supported. When a reference is happening, internally these styles are copied over. I did copy over everything the figma API is offering here. Hope that catches all, anyway please feel free to open another ticket if something is missing.

Happily close this one.

**Comment by mjsxi** [comment]
🙌 Wooooot, awesome! Thanks for adding this!
