### ISSUE TITLE
Exporting References to JSONBin not working?

### ISSUE THREAD

**Issue by iDVB** [gossi/figma-theemo#21]
1. Created JSONBin account
2. Copied `Secret Key / X-Master-Key` to Theemo settings
3. Pasted `Bin URL` into Theemo settings `https://jsonbin.io/[NOTTELLING]`
4. Clicked `Export References` in Theemo Tools
5. Nothing appears to happen? Is there somewhere to see logs / plugin logs?
6. Nothing in JSONBin json object.

What am I doing wrong?

**Comment by iDVB** [comment]
Looks like I have the export working. I had to use the `Access URL` which can't be found anywhere in the JSONBin UI until you "edit" the bin and hit "Update". You don't actually have to make any changes though.
![image](https://user-images.githubusercontent.com/189506/130278993-e2b995f2-75e4-4651-9de8-1406c2aebadd.png)

Now the issue seems to be that only NEW references are being exported? Is there some kinda breakage that happens when you export, where all those refs are than lost? Cause if I go into JSONBin and clear the refs.... and then go back into Figma and hit export again.... its as if there are no refs at all. 

@gossi If this is the expected behavior when clicking export, then perhaps that process should instead be named "Save to JSONBin" as it seems those become the master and local ones will be lost?

**Comment by gossi** [comment]
Hey @iDVB,

where to get the jsonbin url depends on how they make changes on their end. What you have sounds right, but I remember my way of finding it was different.

However, when you hit export in the plugin, it exports _all_ references it can find - that's how it should work.

I made the `Stats` tab in the plugin, so for you to see how many references you have there in total and that's the expected number of references to be exported. Can you check them?

Also, please select a node in figma and have a look if the references are properly shown in theemo plugin. I've had situations where references wheren't mapped properly any longer.

PS. There is only `Stats` tab for real "dumb" inspection of what references are there. Nothing details. If you have ideas, please open an issue with how it could look, what you wanna see in there.

**Comment by i-break-codes** [comment]
Hey folks,

JSONBin.io Author here, would love to understand the use case so that I could help you folks out with the same.

**Comment by iDVB** [comment]
@i-break-codes I think the only feedback I'd have for JSONBin is just that the Bin URL is [buried under the update/edit screen](https://github.com/gossi/figma-theemo/issues/21#issuecomment-902885724), instead of out in the aggregate details of the bin. 

@gossi I think we have Theemo working regarding exporting all references now. However, I'd LOVE more info on how to get these contexts working in other documents, and understand on that can work with Themer.

Right now we have our Design System with Theemo contexts working to showcase the Design System for the different brand colors.... but now we want our Design System "users" to be able to create a new file.... pull out and use a Design System component into their file and choose which Theme/Context that file/page should use for all components. 

It was my understanding that Theemo and Themer can work together do to this?

**Comment by gossi** [comment]
I'm glad this is working now.

@i-break-codes what an honor to have you hear. Thank so much reaching out to provide help and assist smooth handling of your service.

@iDVB Thanks for your feedback. I opened another issue to discuss documenting this better. Let's continue discussing this at #23 (general) and #24 (your particular question).

I gonna close this one.
