### ISSUE TITLE
Is there a screen that shows you all the existing references?

### ISSUE THREAD

**Issue by iDVB** [gossi/figma-theemo#22]
If you delete a style involved in a reference it simply silently errors out in the console about it. 
How would you go about cleaning this up short of manually going into the JSON?

```
Error: in set_paints: The style with id "S:e4c21f9f08cc03dbca7753deba0eeb481a1b8b00," does not exist
    at h (PLUGIN_9_SOURCE)
    at updateStyle (PLUGIN_9_SOURCE)
    at updateStyles (PLUGIN_9_SOURCE)
    at <anonymous> (PLUGIN_9_SOURCE)
    at <anonymous> (PLUGIN_9_SOURCE)
    at each (PLUGIN_9_SOURCE)
    at eachWithHandler (PLUGIN_9_SOURCE)
    at execute (PLUGIN_9_SOURCE)
    at <anonymous> (PLUGIN_9_SOURCE)
```

**Comment by gossi** [comment]
If you select the node in question, where the _origin_ or the _reference_ style are not there any longer, the plugin should show you the "migrate" screen. Where you can select, which style you want to keep, etc.

Was wondering, if I missed a case, where this screen doesn't fit then?

**Comment by iDVB** [comment]
@gossi I'd have to see how the data is mapped regarding these references.... but maybe a screen/tab that just shows ALL references regardless of what you have selected?

Then it could look something like this.... with edit/delete options for each?

Eg. 
![image](https://user-images.githubusercontent.com/189506/131383633-b0bcf654-f439-4514-b27f-1731be4a2282.png)

**Comment by gossi** [comment]
Aha! Sounds interesting. I understand these are two features (maybe in one screen):

1. List all references `a --> b` (or so)
2. Batch references on one screen

Is that correct?

**Comment by iDVB** [comment]
I think thats what I'm saying.... rather than "just" having to hunt down the selections in order to edit your ref?
Does that make sense or do I not understand refs correctly?

**Comment by gossi** [comment]
I'm moving this repo. I'm closing this issue and have split this feature request into two distinct issues:

- gossi/theemo#592
- gossi/theemo#593
