### ISSUE TITLE
Theemo isn't working

### ISSUE THREAD

**Issue by hold-shift** [gossi/figma-theemo#3]
HI, until yesterday, my team were trying Theemo and Switor to switch themes in Figma. Today they don't work, none of them. Thank you in advance

**Comment by gossi** [comment]
I run into the same situation, there were too many references I tried to update (I have 160 in my file).

Last night I pushed a change to made the update interval dynamic. The more references the longer the interval - more like a short-term hack to enable us again. Did that work for you? The version containing the fix is `v9`. If you open the plugin it gives you a `Stats` page (that's how you know you are on v9 for now).

Can you let me know how many references you manage? Would be good to have some other numbers, too.

**Comment by hold-shift** [comment]
Not so many, you can see them in the image attached. For now we are just experimenting on some possibilities trying to find the best workflow for our project. We think contexts fits for us
 
<img width="1257" alt="Captura de pantalla 2020-06-03 a las 18 53 35" src="https://user-images.githubusercontent.com/61543739/83665340-91b93680-a5cb-11ea-9671-c438b5bae31f.png">

**Comment by gossi** [comment]
That's great to hear. Well, what I did was to actually make working with contexts even easier. My idea was, whenever you do some change to let's say `grey.§light` in your screenshot and `light` is your active context, the `grey` would automatically update. Unfortunately that was too much and too much computing was done in the background, that stopped figma from working (for me as well).

The goal stays for me, that theemo is automating the shit out of it 😈 
I at least now have a _benchmark_ to test against and I will make small iterative steps towards this goal now.

Let me know what are your wishes are to support your workflow, pretty sure all of us will benefit 😊

**Comment by hold-shift** [comment]
Yes, that process that you describe fitted for us. We are trying to isolate theme color variables where we are locating those theme changes. The goal is to listen style changes and update all the components whether a group of color changes or just one (we would love to include typography changes too)

This way of creating themes avoids setting up all the components for each theme.

**Comment by gossi** [comment]
Great to hear! I described the process about themes in a series of blog posts:

Overview: https://gos.si/blog/from-figma-to-ember-to-storybook-with-2-clicks/
Full Featured Themes: https://gos.si/blog/full-featured-themes-in-figma/ (that speaks about isolating themes)
Here I rethought tokens: https://gos.si/blog/say-hello-to-theemo-the-yordle-powered-theme-automator/

Which led to: https://gossi.github.io/theemo (that's framework agnostic library to move your design tokens from figma to code) So far I've been using style-dictionary here. If that works for you have a look. If you happen to use theo, let's collaborate to add this to theemo.

That said. I just published another version of figma-theemo. That should resolve the performance issues :)

I gonna close this one. Please open a new issue at a respective theemo repo. Happy to collaborate on more additions.
